export const sNodes = [
  { id: "Tammy Whitney" },
  { id: "\tCLS" },
  { id: "\tIGE" },
  { id: "\tOISA" },
  { id: "GSP organizers" },
  { id: "Student Affairs(?)" },
  { id: "Registrar's Office" },
  { id: "Instructional Support Committee" },
  { id: "Joyce" },
  { id: "Friends and Colleagues" },
  { id: "OISA" },
  { id: "The President" },
  { id: "Vickie Rutherford" },
  { id: "MAP Program(?)" },
  { id: "CLS" },
  { id: "There are money or other resources to support advising?" },
  { id: "Still figuring it out/Not clear/Unsure" },
  {
    id: "Tutorial Program (?)/Tutorial Advising/Tutorial Advising Committee/Worshops for Tutorial Training",
  },
  { id: "Executive Council" },
  { id: "Academic Centers" },
  { id: "Student Resources" },
  { id: "Uncertain" },
  { id: "Staff" },
  { id: "People who hire tutors, SCL's, and other student staff." },
  { id: "Faculty" },
  { id: "Widely Distributed" },
  { id: "Registrar" },
  { id: "Acdemic Centers" },
  { id: "Associate Deans" },
  { id: "Faculty Resources" },
  { id: "Belinda" },
  { id: "$ for Leadership Workshop Attend" },
  { id: "NSO organizers" },
  { id: "Humanities Center" },
  { id: "Kate" },
  { id: "Board of Trustees" },
  { id: "Tim Arner" },
  { id: "IGE" },
  {
    id: "Budgetary decisions on granting new positions in Academic Advising etc",
  },
  { id: "Joyce's Office/Academic Advising" },
  { id: "Wilson Center" },
  { id: "Institution for Global Engagement" },
  { id: "CTLA" },
  { id: "Dean's Office" },
  { id: "The Endowment + Trustees(?)" },
  { id: "Science Learning Center" },
  { id: "Academic Advising" },
  { id: "Higher Administration" },
  { id: "Faculty Workshops" },
  { id: " Dean's Office" },
  { id: " Karla Erickson, Chair" },
  { id: " Vickie Rutherford" },
  { id: " Academic Advising (Joyce's Office)" },
  { id: "Academic Department Leadership" },
  { id: "Myself" },
  { id: " IGE" },
  { id: " RLC" },
  { id: "RLC" },
  { id: " CRSSJ" },
  { id: "CRSSJ" },
  { id: " Faculty/Coaches" },
  { id: " Karen Edwards/Karen Edwards + Office" },
  { id: " Sarah Barks" },
  { id: " Autumn Wilke" },
  { id: " Alicia Stanley - IGE" },
  { id: " CLS" },
  { id: " Student Affairs" },
  {
    id: " All my colleagues really!/My faculty colleagues./Colleagues in departments",
  },
  { id: "  Jae Baldree  accessibility" },
  { id: " Academic Affairs?" },
  { id: " OISA" },
  { id: " Stephanie Jones" },
  { id: " Academic Centers" },
  { id: " Accessibility Disability" },
  { id: "GGE" },
  { id: " GGE" },
  { id: "Accessibility and Disability Resources" },
  { id: " Vanessa Priest" },
  { id: " Joyce Stern" },
  { id: " Ross Haenfler, Former Chair" },
  { id: " Tammy Whitney" },
  { id: " Tutorial Workshop Staff" },
  { id: " First-Gen Group" },
  { id: " Student Resources" },
  { id: " SLC (Science Learning Center)" },
  { id: " Writing/Reading/Speaking" },
  { id: " Disability SUCS" },
  { id: " Senior Faculty" },
  { id: " Joyce + Office" },
  { id: ' Other professors who also advice "seriously"' },
  { id: " Charles Cunningham" },
  { id: " My department chairs" },
  { id: " Kesho Scott" },
  { id: " Academic Advising" },
  { id: " Mellon Mays Advisor" },
  { id: " Higher Administration" },
  { id: " LuAnn Wheeler" },
  { id: " Belinda Backous" },
  { id: " OCS" },
  { id: " ME!" },
  { id: " Tim Arner" },
  { id: " Registrar's Office" },
  { id: " Kate Ferraro" },
  { id: " Faculty Workshops" },
  { id: " Friends and Colleagues" },
  { id: " Catherine Ashton" },
  { id: " Minna Mahlab in Science Learning Center" },
  { id: " Andi Tracy" },
  { id: " Writing Center" },
  { id: " Associate Dean" },
  { id: " Registrar/Registrar's Office" },
];

export const sLinks = [
  { source: "Dean's Office", target: "Higher Administration", value: 9 },
  {
    source: "Joyce's Office/Academic Advising",
    target: "Academic Advising",
    value: 8,
  },
  { source: "Registrar", target: "Registrar's Office", value: 8 },
  {
    source:
      "Tutorial Program (?)/Tutorial Advising/Tutorial Advising Committee/Worshops for Tutorial Training",
    target: "Faculty Workshops",
    value: 5,
  },
  {
    source: "Still figuring it out/Not clear/Unsure",
    target: "Uncertain",
    value: 4,
  },
  { source: "Student Affairs(?)", target: "Student Resources", value: 3 },
  { source: "CTLA", target: "Academic Centers", value: 3 },
  { source: "IGE", target: "\tIGE", value: 2 },
  { source: "Faculty", target: "Friends and Colleagues", value: 2 },
  { source: "Wilson Center", target: "Academic Centers", value: 2 },
  { source: "Joyce", target: "Academic Advising", value: 2 },
  {
    source: "The Endowment + Trustees(?)",
    target: "Board of Trustees",
    value: 1,
  },
  { source: "Widely Distributed", target: "Uncertain", value: 1 },
  { source: "MAP Program(?)", target: "Student Resources", value: 1 },
  { source: "Tim Arner", target: "Higher Administration", value: 1 },
  { source: "OISA", target: "\tOISA", value: 1 },
  {
    source: "Institution for Global Engagement",
    target: "Acdemic Centers",
    value: 1,
  },
  { source: "Humanities Center", target: "Academic Centers", value: 1 },
  { source: "Associate Deans", target: "Higher Administration", value: 1 },
  { source: "Science Learning Center", target: "Academic Centers", value: 1 },
  { source: "Executive Council", target: "Higher Administration", value: 1 },
  {
    source: "There are money or other resources to support advising?",
    target: "Uncertain",
    value: 1,
  },
  {
    source: "Instructional Support Committee",
    target: "Faculty Resources",
    value: 1,
  },
  {
    source: "$ for Leadership Workshop Attend",
    target: "Faculty Workshops",
    value: 1,
  },
  { source: "Belinda", target: "Academic Advising", value: 1 },
  { source: "Kate", target: "Academic Advising", value: 1 },
  { source: "The President", target: "Higher Administration", value: 1 },
  { source: "Tammy Whitney", target: "Registrar's Office", value: 1 },
  { source: "Vickie Rutherford", target: "Registrar's Office", value: 1 },
  {
    source: "People who hire tutors, SCL's, and other student staff.",
    target: "Staff",
    value: 1,
  },
  {
    source:
      "Budgetary decisions on granting new positions in Academic Advising etc",
    target: "Higher Administration",
    value: 1,
  },
  { source: "NSO organizers", target: "Staff", value: 1 },
  { source: "GSP organizers", target: "Staff", value: 1 },
  { source: "Academic Advising", target: " Joyce Stern", value: 17 },
  {
    source: "Academic Advising",
    target: " Academic Advising (Joyce's Office)",
    value: 12,
  },
  { source: "Friends and Colleagues", target: " Faculty/Coaches", value: 8 },
  { source: "CLS", target: "\tCLS", value: 19 },
  { source: "Academic Advising", target: " Belinda Backous", value: 7 },
  {
    source: "Friends and Colleagues",
    target:
      " All my colleagues really!/My faculty colleagues./Colleagues in departments",
    value: 4,
  },
  { source: "Registrar's Office", target: " Vickie Rutherford", value: 4 },
  { source: "\tIGE", target: " OCS", value: 4 },
  {
    source: "Registrar's Office",
    target: " Registrar/Registrar's Office",
    value: 3,
  },
  { source: "Registrar's Office", target: " Tammy Whitney", value: 3 },
  { source: "OISA", target: " Karen Edwards/Karen Edwards + Office", value: 3 },
  { source: "Higher Administration", target: " Dean's Office", value: 3 },
  { source: "Academic Advising", target: " Joyce + Office", value: 3 },
  {
    source: "Academic Department Leadership",
    target: " Karla Erickson, Chair",
    value: 2,
  },
  { source: "Student Resources", target: " Student Affairs", value: 2 },
  { source: "Faculty Workshops", target: " Tutorial Workshop Staff", value: 2 },
  { source: "Registrar's Office", target: " Catherine Ashton", value: 2 },
  { source: "\tCLS", target: " Sarah Barks", value: 2 },
  { source: "Academic Advising", target: " Kate Ferraro", value: 2 },
  {
    source: "Academic Centers",
    target: " Minna Mahlab in Science Learning Center",
    value: 2,
  },
  { source: "Higher Administration", target: " Tim Arner", value: 2 },
  {
    source: "Academic Department Leadership",
    target: " Ross Haenfler, Former Chair",
    value: 1,
  },
  {
    source: "Accessibility and Disability Resources",
    target: " Autumn Wilke",
    value: 1,
  },
  {
    source: "Friends and Colleagues",
    target: " Mellon Mays Advisor",
    value: 1,
  },
  { source: "Friends and Colleagues", target: " Senior Faculty", value: 1 },
  { source: "Academic Centers", target: " Vanessa Priest", value: 1 },
  { source: "Higher Administration", target: " Andi Tracy", value: 1 },
  { source: "Friends and Colleagues", target: " Stephanie Jones", value: 1 },
  {
    source: "Accessibility and Disability Resources",
    target: " Accessibility Disability",
    value: 1,
  },
  {
    source: "Accessibility and Disability Resources",
    target: "  Jae Baldree  accessibility",
    value: 1,
  },
  { source: "Academic Centers", target: " Writing Center", value: 1 },
  { source: "Academic Centers", target: " Writing/Reading/Speaking", value: 1 },
  {
    source: "Academic Centers",
    target: " SLC (Science Learning Center)",
    value: 1,
  },
  { source: "Myself", target: " ME!", value: 1 },
  {
    source: "Friends and Colleagues",
    target: ' Other professors who also advice "seriously"',
    value: 1,
  },
  { source: "GGE", target: " GGE", value: 1 },
  { source: "CRSSJ", target: " First-Gen Group", value: 1 },
  { source: "IGE", target: " Alicia Stanley - IGE", value: 1 },
  { source: "RLC", target: " RLC", value: 1 },
  { source: "Friends and Colleagues", target: " Kesho Scott", value: 1 },
  { source: "Higher Administration", target: " Disability SUCS", value: 1 },
  { source: "Higher Administration", target: " Associate Dean", value: 1 },
  { source: "Student Resources", target: " Academic Affairs?", value: 1 },
  {
    source: "Academic Department Leadership",
    target: " Charles Cunningham",
    value: 1,
  },
  {
    source: "Academic Department Leadership",
    target: " My department chairs",
    value: 1,
  },
  { source: "Registrar's Office", target: " LuAnn Wheeler", value: 1 },
];
